#!/usr/bin/env bash
# ihelped.ai — idempotent first-time server bootstrap.
#
# Run once against a fresh server (or safely re-run). Handles everything that
# `deploy.sh` assumes is already in place:
#   - /var/www/ihelped.ai with www-data ownership
#   - /etc/ihelped.env populated with generated secrets (kept if it exists)
#   - pnpm installed globally on the server
#   - HTTP-only nginx site enabled and reloaded
#   - systemd unit installed, enabled, but not started (no code yet)
#
# After this runs you can `./deploy/deploy.sh` to ship code. TLS is a separate
# step via `./deploy/tls-setup.sh`, done only once DNS points at this box.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
if [[ -f "${REPO_ROOT}/.env.deploy" ]]; then
  set -o allexport
  # shellcheck disable=SC1091
  source "${REPO_ROOT}/.env.deploy"
  set +o allexport
fi

HOST="${IHELPED_DEPLOY_HOST:-calmerapy}"
REMOTE_ROOT="${IHELPED_DEPLOY_ROOT:-/var/www/ihelped.ai}"
ENV_FILE="${IHELPED_REMOTE_ENV_FILE:-/etc/ihelped.env}"

if [[ -z "${REMOTE_ROOT}" || "${REMOTE_ROOT}" == "/" || "${REMOTE_ROOT}" == "." ]]; then
  echo "[bootstrap] refusing unsafe REMOTE_ROOT='${REMOTE_ROOT}'" >&2
  exit 1
fi

echo "[bootstrap] ship nginx + systemd artifacts to ${HOST}"
ssh "${HOST}" "mkdir -p /tmp/ihelped-bootstrap"
rsync -az \
  "${SCRIPT_DIR}/nginx/ihelped.ai.http-only.conf" \
  "${SCRIPT_DIR}/nginx/ihelped.ai.conf" \
  "${SCRIPT_DIR}/systemd/ihelped-api.service" \
  "${HOST}:/tmp/ihelped-bootstrap/"

echo "[bootstrap] run remote bootstrap script"
ssh "${HOST}" sudo sh -s -- "${REMOTE_ROOT}" "${ENV_FILE}" <<'REMOTE_SCRIPT'
set -eu
remote_root="$1"
env_file="$2"
staging="/tmp/ihelped-bootstrap"

echo "[remote] ensure ${remote_root} exists with www-data ownership"
mkdir -p "${remote_root}/dist" \
         "${remote_root}/server/dist" \
         "${remote_root}/server/deploy/schema"
chown -R www-data:www-data "${remote_root}"

echo "[remote] ensure ${env_file} (kept intact if already present)"
if [ ! -f "${env_file}" ]; then
  ip_salt="$(head -c 32 /dev/urandom | base64 | tr -d '=/+' | cut -c1-48)"
  session_secret="$(head -c 32 /dev/urandom | base64 | tr -d '=/+' | cut -c1-48)"
  umask 077
  cat > "${env_file}" <<EOF_ENV
# /etc/ihelped.env — generated by deploy/bootstrap.sh.
# Edit freely; deploy.sh only manages the APP_VERSION line.
NODE_ENV=production
BIND_HOST=127.0.0.1
PORT=3001
PUBLIC_URL=https://ihelped.ai

IP_HASH_SALT=${ip_salt}
ADMIN_SESSION_SECRET=${session_secret}

# SQLite is the safest fresh-bootstrap default. Run deploy/mysql-setup.sh to
# provision the production MySQL schema, flip STORE=mysql, and set MYSQL_URL.
STORE=sqlite
SQLITE_PATH=${remote_root}/data/ihelped.db

# SEARCH: set to 'meili' once a scoped API key has been provisioned on the
# shared Meilisearch instance (indexes restricted to ihelpedai_*).
SEARCH=sql
# MEILI_URL=http://127.0.0.1:7700
# MEILI_KEY=<scoped key for ihelpedai_* indexes>

# RedisRateLimiter is implemented (atomic Lua-script multi-bucket). Default
# stays RATE_LIMIT=memory so a fresh bootstrap on a host without Redis still
# boots; flip to redis once the local Redis is reachable on REDIS_URL.
RATE_LIMIT=memory
# RATE_LIMIT=redis
# REDIS_URL=redis://127.0.0.1:6379

# SmtpMailer is implemented (nodemailer). Flip to MAILER=smtp and set
# SMTP_URL only AFTER the self-hosted postfix + opendkim stack is configured
# (see docs/reports/mail-setup.md). Default stays MAILER=file so a fresh
# bootstrap never attempts to connect to an unconfigured SMTP endpoint.
MAILER=file
# MAILER=smtp
# SMTP_URL=smtp://127.0.0.1:25
MAIL_FROM=noreply@ihelped.ai

DEV_RATE_MULTIPLIER=1
EOF_ENV
  chown www-data:www-data "${env_file}"
  chmod 600 "${env_file}"
  echo "[remote] wrote ${env_file} with generated secrets"
else
  echo "[remote] ${env_file} already exists — leaving untouched"
fi

echo "[remote] ensure SQLite data dir"
mkdir -p "${remote_root}/data"
chown -R www-data:www-data "${remote_root}/data"

echo "[remote] install Node + npm pinned to match CI"
NODE_VERSION="20.20.2"
have_pinned_node=0
if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
  if [ "$(node -v)" = "v${NODE_VERSION}" ]; then
    have_pinned_node=1
  fi
fi
if [ "${have_pinned_node}" -ne 1 ]; then
  if ! command -v curl >/dev/null 2>&1; then
    apt-get update -y
    apt-get install -y curl
  fi
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y "nodejs=${NODE_VERSION}-1nodesource1" \
    || apt-get install -y nodejs
  # NodeSource occasionally drops older minor versions, in which case the
  # fallback above silently installs whatever ships there. Surface that drift
  # so a deploy doesn't end up running a different Node than CI.
  installed_node="$(node -v 2>/dev/null || echo unknown)"
  if [ "${installed_node}" != "v${NODE_VERSION}" ]; then
    echo "[remote] WARNING: installed Node ${installed_node}, expected v${NODE_VERSION}" >&2
  fi
fi

echo "[remote] install expected pnpm globally"
PNPM_VERSION=10.15.1
if ! command -v pnpm >/dev/null 2>&1 || [ "$(pnpm -v)" != "${PNPM_VERSION}" ]; then
  npm install -g "pnpm@${PNPM_VERSION}"
fi

echo "[remote] install nginx if missing"
if ! command -v nginx >/dev/null 2>&1; then
  apt-get update -y
  apt-get install -y nginx
fi

echo "[remote] install HTTP-only nginx site"
install -m 0644 "${staging}/ihelped.ai.http-only.conf" /etc/nginx/sites-available/ihelped.ai.conf
ln -sf /etc/nginx/sites-available/ihelped.ai.conf /etc/nginx/sites-enabled/ihelped.ai.conf
# Stash the target HTTPS config; tls-setup.sh installs it after certbot runs.
install -m 0644 "${staging}/ihelped.ai.conf" /etc/nginx/sites-available/ihelped.ai.target.conf
# The HTTPS target config `include`s /etc/nginx/snippets/ihelped-allowlist.conf.
# Create it empty so `nginx -t` passes before any IPs have been added. Edit in
# place to add beta-tester IPs without a repo commit — one `<ip>  1;` per line.
if [ ! -f /etc/nginx/snippets/ihelped-allowlist.conf ]; then
  mkdir -p /etc/nginx/snippets
  cat > /etc/nginx/snippets/ihelped-allowlist.conf <<'ALLOWLIST'
# ihelped.ai restricted-beta allowlist. One entry per line, e.g.:
#   203.0.113.42   1;
ALLOWLIST
fi

echo "[remote] nginx -t"
nginx -t
echo "[remote] nginx reload"
nginx -s reload

echo "[remote] install systemd unit"
install -m 0644 "${staging}/ihelped-api.service" /etc/systemd/system/ihelped-api.service
systemctl daemon-reload
systemctl enable ihelped-api.service

echo "[remote] cleanup staging"
rm -rf "${staging}"

echo "[remote] bootstrap complete."
REMOTE_SCRIPT

echo "[bootstrap] done."
echo
echo "next:"
echo "  1) ./deploy/deploy.sh        # ships code + starts API"
echo "  2) point DNS A records for ihelped.ai and www.ihelped.ai"
echo "     at this server (public IP on the box)"
echo "  3) ./deploy/tls-setup.sh     # runs certbot and installs HTTPS config"
